In [5]:
import numpy as np
l = []
for i in range(1,5):
    int_1 = int(input("Enter a number: "))
    l.append(int_1)
print("The array is: ",np.array(l))

Enter a number:  12
Enter a number:  13
Enter a number:  14
Enter a number:  15


The array is:  [12 13 14 15]


In [8]:
x=[2,3,4,5,6]
y=np.array([1,2,3,4,5,6,7])
print(y)
print(type(y))
print("The dim of array is:",y.ndim)

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
The dim of array is: 1


In [9]:
arr2=np.array([[1,2,3,4,5,6,7]])
print(arr2)
print(type(arr2))
print("The dim of array is:",arr2.ndim)

[[1 2 3 4 5 6 7]]
<class 'numpy.ndarray'>
The dim of array is: 2


In [17]:
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)
print(type(arr3))
print("The dim of array is:",arr3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>
The dim of array is: 3


In [19]:
arr=np.array([1,2,3],ndmin =10)
print(arr)
print(type(arr))
print("The dim of array is:",arr.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
<class 'numpy.ndarray'>
The dim of array is: 10
