In [13]:
#Zeros
import numpy as np
ar_zero = np.zeros(4)
print(ar_zero)

print()

ar_zero1 = np.zeros((3,4)) #Dimension
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
#Ones
ar_one = np.ones(4)
print(ar_one)

print()

ar_one1 = np.ones((3,4)) #Dimension
print(ar_one1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
#empty array
ar_em = np.empty(4) #previous data comes in it
print(ar_em)

[1. 1. 1. 1.]


In [17]:
#range array
arr_rn = np.arange(4)
print(arr_rn)

[0 1 2 3]


In [20]:
#diagonal with 1
ar_dia = np.eye(3)
print(ar_dia)

print()

ar_dia1 = np.eye(3,5)
print(ar_dia1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [21]:
#linspace
ar_lin = np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]
